application: twitter-atom
version: 2
runtime: python27
threadsafe: true
api_version: 1
default_expiration: 1d

# background: https://github.com/snarfed/bridgy/issues/578
automatic_scaling:
  max_idle_instances: 1
  max_concurrent_requests: 12

libraries:
- name: django
  version: 1.3
- name: ssl
  version: latest

builtins:
- remote_api: on

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /
  static_files: static/index.html
  upload: static/index.html
  secure: always

- url: /(generate|oauth_callback)
  script: main.application
  secure: always

- url: /atom
  script: main.application
  secure: always

skip_files:
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?(debian|docs?|examples?|l|pydocs?|python3|ref|samples?|tests?)/.*
