application: twitter-atom
version: 2
runtime: python27
threadsafe: true
api_version: 1
default_expiration: 1d

libraries:
- name: django
  version: 1.3

builtins:
- remote_api: on

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /(generate|oauth_callback)
  script: main.application

- url: /atom
  script: main.application
  secure: always

skip_files:
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
# don't need anything in the tweepy or webapp-improved subdirs, especially since
# webapp-improved/lib/ has over 1k files!
- activitystreams/tweepy_submodule/(docs|examples|tools)/.*
- activitystreams/webutil/webapp-improved/.*/.*
